src/Entity/Answer.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Connectors\AnswerListener;
use App\Repository\AnswerRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Ответы на задания по sql
 */
#[ORM\Entity(repositoryClass: AnswerRepository::class)]
#[ORM\EntityListeners([AnswerListener::class])]
#[ApiResource]
class Answer
{
    #[ORM\Id]
    #[ORM\Column(type: 'string')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Question::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $question;

    /**
     * @var string sql-запрос, по сути значимая часть ответа
     */
    #[ORM\Column(type: 'text')]
    private $sql_text = '';

    /**
     * @var array результат ответа, который видел студнет во время ответа на вопрос, если запрос был выполнен.
     */
    #[ORM\Column(type: 'array', nullable: true)]
    private $result_table;

    /**
     * @var string Ошбка запроса, отданая базой данных, если при запросе случилась ошибка
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $result_error;

    #[ORM\Column(type: 'text', nullable: true)]
    private $check_right;

    /**
     * @var
     */
    #[ORM\Column(type: 'datetime', nullable: true)]
    private $start;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $end;

    #[ORM\ManyToOne(targetEntity: ExaminationSheet::class, inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private $examinationSheet;

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getSqlText(): ?string
    {
        return $this->sql_text;
    }

    public function setSqlText(string $sql_text): self
    {
        $this->sql_text = $sql_text;

        return $this;
    }

    public function getResultTable(): ?array
    {
        return $this->result_table;
    }

    public function setResultTable(?array $result_table): self
    {
        $this->result_table = $result_table;

        return $this;
    }

    public function getResultError(): ?string
    {
        return $this->result_error;
    }

    public function setResultError(?string $result_error): self
    {
        $this->result_error = $result_error;

        return $this;
    }

    public function getCheckRight(): ?string
    {
        return $this->check_right;
    }

    public function setCheckRight(?string $check_right): self
    {
        $this->check_right = $check_right;

        return $this;
    }

    public function getStart(): ?DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getExaminationSheet(): ?ExaminationSheet
    {
        return $this->examinationSheet;
    }

    public function setExaminationSheet(?ExaminationSheet $examinationSheet): self
    {
        $this->examinationSheet = $examinationSheet;

        return $this;
    }
}

src/Form/AnswerType.php
<?php

namespace App\Form;

use App\Entity\Answer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnswerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sql_text')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Answer::class,
        ]);
    }
}

src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Connectors\IdGenerator;
use App\Connectors\PdoConnection;
use App\Connectors\TimeLimitCalculator;
use App\Connectors\TimeLimitExam;
use App\Connectors\TimeLimitQuestion;
use App\Entity\Answer;
use App\Entity\ExaminationSheet;
use App\Entity\Question;
use App\Entity\User;
use App\Form\AnswerType;
use App\Repository\AnswerRepository;
use App\Repository\ExaminationSheetRepository;
use App\Repository\ExamRepository;
use App\Repository\QuestionRepository;
use App\Service\CheckRight\ExamCheckRight;
use DateTime;
use DateTimeInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/answer')]
class AnswerController extends AbstractController
{
    public function __construct(private PdoConnection $studentConnection)
    {
    }

    #[Route('/', name: 'app_answer_index', methods: ['GET'])]
    public function index(
        AnswerRepository $answerRepository,
        Security $security
    ): Response {
        /** @var User $user */
        $user = $security->getUser();
        $answers = $answerRepository->findAll();
        if (
            in_array('ROLE_TEACHER', $user->getRoles())
            || in_array('ROLE_ADMIN', $user->getRoles())
        ) {
            return $this->render('answer/index.html.twig', [
                'answers' => $answers,
            ]);
        }
        else {
            $answersFiltered = [];

            foreach ($answers as $answer) {
                if ($answer->getExaminationSheet()->getStudent()->getId() === $user->getId()) {
                    $answersFiltered[] = $answer;
                }
            }

            return $this->render('answer/index.html.twig', [
                'answers' => $answersFiltered,
            ]);
        }
    }

    #[Route('/new', name: 'app_answer_new', methods: ['GET'])]
    public function new(
        Request                    $request,
        AnswerRepository           $answerRepository,
        ExaminationSheetRepository $examinationSheetRepository,
        ExamRepository             $examRepository,
        QuestionRepository         $questionRepository,
        Security                   $security
    ): Response {
        $start = new DateTime();
        if ($request->get('exam')) {
            /** @var User $user */
            $user = $security->getUser();
            $exam = $examRepository->find($request->get('exam'));
            $sheets = $exam->getExaminationSheetByUserId($user->getId());

            if (!$sheets->isEmpty()) {
                $sheet = $sheets->last();
                $question = $sheet->getQuestions()->last();
            }
            else {
                $questions = $this->getOrderedQuestion($exam->getQuestions()->toArray());
                $question = $questions[0];
                $sheet = new ExaminationSheet();
                $sheet->setExam($exam)
                    ->setStudent($user)
                    ->setId((new IdGenerator())->generateQuestionId());
                $examinationSheetRepository->add($sheet);
            }
        }
        elseif ($request->get('answer')) {
            $answer = $answerRepository->find($request->get('answer'));
            $sheet = $answer->getExaminationSheet();
            $start = $answer->getStart();
            $question = $answer->getQuestion();
        }
        elseif ($request->get('sheet') && $request->get('question')) {
            $question = $questionRepository->find($request->get('question'));
            $sheet = $examinationSheetRepository->find($request->get('sheet'));
        }
        else {
            throw new NotFoundHttpException('No exam id');
        }

        $answer = new Answer();
        $answer->setQuestion($question)
            ->setStart($start)
            ->setSqlText('')
            ->setExaminationSheet($sheet)
            ->setId((new IdGenerator())->generateQuestionId());
        $answerRepository->add($answer);
        return $this->redirectToRoute('app_answer_run', ['id' => $answer->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_answer_show', methods: ['GET'])]
    public function show(Answer $answer): Response
    {
        return $this->render('answer/show.html.twig', [
            'answer' => $answer,
            'nextQuestion' => $this->getNextQuestion($answer),
            'limit' => $this->getLimit($answer, new DateTime()),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_answer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Answer $answer, AnswerRepository $answerRepository): Response
    {
        $checkRight = new ExamCheckRight();

        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            try {
                $result = $this->studentConnection->fetchAll($answer->getSqlText());
                $answer->setResultTable($result);
                $answer->setResultError('');
            } catch (Exception $e) {
                $answer->setResultTable([]);
                $answer->setResultError($e->getMessage());
            }

            $answerRepository->add($checkRight->getCheckedAnswer($answer));
            return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('answer/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'limit' => $this->getLimit($answer, new DateTime()),
        ]);
    }

    #[Route('/{id}/run', name: 'app_answer_run', methods: ['GET', 'POST'])]
    public function run(
        Request $request,
        Answer $answer,
        AnswerRepository $answerRepository
    ): Response {
        $now = new DateTime();
        $checkRight = new ExamCheckRight();

        $limit = $this->getLimit($answer, $now);

        if ($limit < 0) {
            $answer->setEnd($now);
            $answerRepository->add($answer);
            $nextQuestion = $this->getNextQuestion($answer);
            return $nextQuestion

                ? $this->redirectToRoute('app_answer_new', [
                    'question' => $nextQuestion->getId(),
                    'sheet' => $answer->getExaminationSheet()->getId(),
                ], Response::HTTP_SEE_OTHER)

                : $this->redirectToRoute('app_examination_sheet_show', [
                    'id' => $answer->getExaminationSheet()->getId(),
                ], Response::HTTP_SEE_OTHER);
        }

        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if (!$answer->getEnd() && $form->isSubmitted() && $form->isValid()) {

            try {
                $result = $this->studentConnection->fetchAll($answer->getSqlText());
                $answer->setResultTable($result)
                    ->setEnd($now);
            } catch (Exception $e) {
                $answer->setResultError($e->getMessage())
                    ->setEnd($now);
            }

            $answerRepository->add($checkRight->getCheckedAnswer($answer, $now));

            return $this->redirectToRoute('app_answer_show', [
                'id' => $answer->getId()
            ], Response::HTTP_SEE_OTHER);
        }

        $tableRowLimit = PdoConnection::VIEW_LIMIT;

        return $this->renderForm('answer/run.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'limit' => $limit,
            'tableRowLimit' => $tableRowLimit,
            'studentData' => $this->studentConnection->getDatabaseData($tableRowLimit),
        ]);
    }

    #[Route('/{id}', name: 'app_answer_delete', methods: ['POST'])]
    public function delete(Request $request, Answer $answer, AnswerRepository $answerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $answer->getId(), $request->request->get('_token'))) {
            $answerRepository->remove($answer);
        }

        return $this->redirectToRoute('app_answer_index', [], Response::HTTP_SEE_OTHER);
    }

    private function getOrderedQuestion(array $questions): array
    {
        usort($questions, function (Question $a, Question $b) {
            $result = $a->getOrd() <=> $b->getOrd();
            if (!$result) {
                return $a->getContent() <=> $b->getContent();
            }

            return $result;
        });
        return $questions;
    }

    private function getNextQuestion(Answer $answer): ?Question
    {
        $questions = $this->getOrderedQuestion($answer->getExaminationSheet()->getExam()->getQuestions()->toArray());
        $question = $answer->getQuestion();
        $questionFind = false;
        foreach ($questions as $variant) {
            if ($questionFind) {
                return $variant;
            }
            if ($question->getId() == $variant->getId()) {
                $questionFind = true;
            }
        }

        return null;
    }

    private function getLimit(Answer $answer, DateTimeInterface $now): int
    {
        $calculator = new TimeLimitCalculator($now);
        $questionLimit = $calculator->getLimit(new TimeLimitQuestion($answer));
        $examLimit = $calculator->getLimit(new TimeLimitExam($answer));
        if ($questionLimit && $examLimit) {
            return min($questionLimit, $examLimit);
        }
        return $questionLimit ?: $examLimit;
    }
}

templates/answer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Edit Answer'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Edit Answer'|trans }}</h1>

    {{ 'Question: '|trans }}{{ answer.getQuestion().getContent() }}

    {{ include('components/_form.html.twig', {
        'action': 'edit',
        'entity': answer,
        'entityName': 'answer'
    }) }}

    <details>
        <summary>
            <span class="dropdown hollow button">Просмотреть БД <i class="arrow-only"></i></span>
        </summary>

        <ul class="tabs"
            data-deep-link="true"
            data-update-history="true"
            data-deep-link-smudge="true"
            data-tabs id="deeplinked-tabs"
        >
            {% for tableName in studentData|keys %}
                <li class="tabs-title">
                    <a href="#{{ tableName ~ '_tab' }}">
                        {{ 'Table `%table%`'|trans({'%table%': tableName}) }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div class="tabs-content" data-tabs-content="deeplinked-tabs">
            {% for tableName, table in studentData %}
            <div id="{{ tableName ~ '_tab' }}" class="tabs-panel">
                <table style="width: auto">
                    <tr>
                        {% for attr in table[0]|keys %}
                            <th style="text-align: left">{{ attr }}</th>
                        {% endfor %}
                    </tr>
                    {% for row in table %}
                        <tr>
                            {% for col in row %}
                                <td>
                                    {{ col }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            {% endfor %}
        </div>
    </details>
{% endblock %}

templates/answer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Answer index'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Answer index'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ '№'|trans }}</th>
                <th>{{ 'Sql_text'|trans }}</th>
                <th>{{ 'Start'|trans }}</th>
                <th>{{ 'End'|trans }}</th>
                <th>{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for key, answer in answers %}
            <tr>
                <td>{{ (key + 1) }}</td>
                <td>
                    <p>{{ answer.sqlText }}</p>
                    <hr/>
                    <div style="color: #999">
                        <div>{{ 'Answer ID'|trans }}: {{ answer.id }}</div>
                        <div>{{ 'Exam'|trans }}: {{ answer.examinationSheet.exam.description }}</div>
                        <div>{{ answer.examinationSheet.student.email }}</div>
                    </div>
                </td>
                <td>{{ answer.start ? answer.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ answer.end ? answer.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    {{ include('components/_actions.html.twig', {
                        'action': 'list',
                        'entity': answer,
                        'entityName': 'answer'
                    }) }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">{{ 'no records found'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/answer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'New Answer'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Create new Answer'|trans }}</h1>

    {{ include('components/_form.html.twig', {
        'action': 'new',
        'entityName': 'answer'
    }) }}

{% endblock %}

templates/answer/run.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Your answer'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Question %number%'|trans({'%number%': answer.question.ord}) }}</h1>

    <div>
        <p>{{ 'Question'|trans({'number': answer.question.ord}) }}:</p>
        <p>{{ answer.getQuestion().getContent() }}</p>
    </div>

    {{ form_start(form) }}
        {{ form_row(form.sql_text, {
            'label': 'You sql text'|trans
        }) }}
        {{ form_widget(form) }}
    {% if resultTable %}
        <p>{{ 'Result of your request'|trans }}</p>
        <table>
            <thead>
            <tr>
                {% for key in resultTable[0]|keys %}
                    <th>{{ key }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for row in resultTable %}
                <tr>
                    {% for value in row %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
        <details open="open">
        <summary>
            <span class="dropdown hollow button">{{ 'Show DataBase'|trans }} <i class="arrow-only"></i></span>
        </summary>

        <p>{{ plural([
                'Table content is hidden'|trans,
                'Вы видите лишь %d строку каждой таблицы'|trans,
                'Вы видите лишь %d строки каждой таблицы'|trans,
                'Вы видите лишь %d строк каждой таблицы'|trans,
            ], 10) }}</p>

        <ul class="tabs"
            data-deep-link="true"
            data-update-history="true"
            data-deep-link-smudge="true"
            data-tabs id="deeplinked-tabs"
        >
            {% for tableName in studentData|keys %}
                <li class="tabs-title">
                    <a href="#{{ tableName ~ '_tab' }}">
                        {{ 'Table `%table%`'|trans({'%table%': tableName}) }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div class="tabs-content" data-tabs-content="deeplinked-tabs">
            {% for tableName, table in studentData %}
                <div id="{{ tableName ~ '_tab' }}" class="tabs-panel">
                    <table style="width: auto">
                        <caption>`{{ tableName }}`</caption>
                        <tr>
                            {% for attr in table[0]|keys %}
                                <th style="text-align: left">{{ attr }}</th>
                            {% endfor %}
                        </tr>
                        {% for row in table %}
                            <tr>
                                {% for col in row %}
                                    <td>
                                        {{ col }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
        </div>
    </details>

        <div class="control">
            <button class="button is-primary">{{ 'Execute query'|trans }}</button>
            <button class="button success">{{ 'Done'|trans }}</button>
            {% if nextQuestion %}
                <a href="{{ path('app_answer_new', {
                    'sheet': answer.getExaminationSheet().getId(),
                    'question': nextQuestion.getId()})
                }}" class="button hollow">
                    {{ 'Next question'|trans }}
                </a>
            {% endif %}
        </div>
    {{ form_end(form) }}

{% endblock %}

templates/answer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Answer'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Answer'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>{{ 'Question'| trans }}</th>
                <td colspan="2">{{ answer.getQuestion().getContent() }}</td>
            </tr>
            <tr>
                <th>{{ 'Sql_text'| trans }}</th>
                <td colspan="2">{{ answer.sqlText }}</td>
            </tr>
            <tr>
                <th>{{ 'Check_right'| trans }}</th>
                <td colspan="2">{{ answer.checkRight }}</td>
            </tr>
            <tr>
                <th>{{ 'Result table'| trans }}</th>
                <td colspan="2">
                    {% if answer.resultTable %}
                    <table>
                        <thead>
                            <tr>
                                {% for key in answer.resultTable[0]|keys %}
                                <th>{{ key }}</th>
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in answer.resultTable %}
                                <tr>
                                    {% for value in row %}
                                    <td>{{ value }}</td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </td>
            </tr>
            {% if answer.resultError is not null  %}
            <tr>
                <th>{{ 'Result error'| trans }}</th>
                <td>{{ answer.resultError }}</td>
            </tr>
            {% endif %}
            <tr>
                <th>{{ 'Start'| trans }}</th>
                <td>{{ answer.start ? answer.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>{{ 'End'| trans }}</th>
                <td>{{ answer.end ? answer.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    {% if limit >= 0 %}
    <a href="{{ path('app_answer_new', {'answer': answer.getId()}) }}" class="button">{{ ''}}Повторить попытку</a>
    {% if nextQuestion %}
        <a href="{{ path('app_answer_new', {'sheet': answer.getExaminationSheet().getId(), 'question': nextQuestion.getId()}) }}" class="button">Следующий вопрос</a>
        {% else %}
            <a href="{{ path('app_examination_sheet_show', {'id': answer.getExaminationSheet().getId()}) }}" onclick="alert(&quot;Вы ответили на последний вопрос. Можете перейти на список ваших ответов.&quot;)" class="button">Финал</a>
    {% endif %}
        {% else %}
        <a href="{{ path('app_examination_sheet_show', {'id': answer.getExaminationSheet().getId()}) }}" class="button">Посмотреть экзаменационный лист</a>
    {% endif %}
{% endblock %}

templates/answer/start.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Your answer'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Question %number%'|trans({'%number%': answer.question.ord}) }}</h1>

    <div>
        <p>{{ 'Question'|trans({'number': answer.question.ord}) }}:</p>
        <p>{{ answer.getQuestion().getContent() }}</p>
    </div>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="control">
            <button class="button is-primary">{{ 'Done'|trans }}</button>
        </div>
    {{ form_end(form) }}

    <details>
        <summary>
            <span class="dropdown hollow button">{{ 'Show DataBase'|trans }} <i class="arrow-only"></i></span>
        </summary>

        <ul class="tabs"
            data-deep-link="true"
            data-update-history="true"
            data-deep-link-smudge="true"
            data-tabs id="deeplinked-tabs"
        >
            {% for tableName in studentData|keys %}
                <li class="tabs-title">
                    <a href="#{{ tableName ~ '_tab' }}">
                        {{ 'Table `%table%`'|trans({'%table%': tableName}) }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div class="tabs-content" data-tabs-content="deeplinked-tabs">
            {% for tableName, table in studentData %}
            <div id="{{ tableName ~ '_tab' }}" class="tabs-panel">
                <table style="width: auto">
                    <tr>
                        {% for attr in table[0]|keys %}
                            <th style="text-align: left">{{ attr }}</th>
                        {% endfor %}
                    </tr>
                    {% for row in table %}
                        <tr>
                            {% for col in row %}
                                <td>
                                    {{ col }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            {% endfor %}
        </div>
    </details>
{% endblock %}