src/Entity/Answer.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Connectors\AnswerListener;
use App\Repository\AnswerRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Ответы на задания по sql
 */
#[ORM\Entity(repositoryClass: AnswerRepository::class)]
#[ORM\EntityListeners([AnswerListener::class])]
#[ApiResource]
class Answer
{
    #[ORM\Id]
    #[ORM\Column(type: 'string')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Question::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $question;

    /**
     * @var string sql-запрос, по сути значимая часть ответа
     */
    #[ORM\Column(type: 'text')]
    private $sql_text = '';

    /**
     * @var array результат ответа, который видел студнет во время ответа на вопрос, если запрос был выполнен.
     */
    #[ORM\Column(type: 'array', nullable: true)]
    private $result_table;

    /**
     * @var string Ошбка запроса, отданая базой данных, если при запросе случилась ошибка
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $result_error;

    #[ORM\Column(type: 'text', nullable: true)]
    private $check_right;

    /**
     * @var
     */
    #[ORM\Column(type: 'datetime', nullable: true)]
    private $start;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $end;

    #[ORM\ManyToOne(targetEntity: ExaminationSheet::class, inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private $examinationSheet;

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getSqlText(): ?string
    {
        return $this->sql_text;
    }

    public function setSqlText(string $sql_text): self
    {
        $this->sql_text = $sql_text;

        return $this;
    }

    public function getResultTable(): ?array
    {
        return $this->result_table;
    }

    public function setResultTable(?array $result_table): self
    {
        $this->result_table = $result_table;

        return $this;
    }

    public function getResultError(): ?string
    {
        return $this->result_error;
    }

    public function setResultError(?string $result_error): self
    {
        $this->result_error = $result_error;

        return $this;
    }

    public function getCheckRight(): ?string
    {
        return $this->check_right;
    }

    public function setCheckRight(?string $check_right): self
    {
        $this->check_right = $check_right;

        return $this;
    }

    public function getStart(): ?DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getExaminationSheet(): ?ExaminationSheet
    {
        return $this->examinationSheet;
    }

    public function setExaminationSheet(?ExaminationSheet $examinationSheet): self
    {
        $this->examinationSheet = $examinationSheet;

        return $this;
    }
}

src/Entity/ExaminationSheet.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ExaminationSheetRepository;
use DateInterval;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExaminationSheetRepository::class)]
#[ApiResource]
class ExaminationSheet
{
    #[ORM\Id]
    #[ORM\Column(type: 'string')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private $student;

    #[ORM\ManyToOne(targetEntity: Exam::class, inversedBy: 'examinationSheets')]
    #[ORM\JoinColumn(nullable: false)]
    private $exam;

    #[ORM\OneToMany(mappedBy: 'examinationSheet', targetEntity: Answer::class, orphanRemoval: true)]
    private $answers;

    #[ORM\ManyToMany(targetEntity: Question::class, inversedBy: 'examinationSheets')]
    private $questions;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getStudent(): ?User
    {
        return $this->student;
    }

    public function setStudent(?User $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getExam(): ?Exam
    {
        return $this->exam;
    }

    public function setExam(?Exam $exam): self
    {
        $this->exam = $exam;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    /**
     * @param int $userId
     * @return Answer|null
     */
    public function getAnswerByUserId(int $userId): ?Answer
    {
        $result = $this->answers->filter(function (Answer $answer, $key) use ($userId) {
            return $answer->getExaminationSheet()->getStudent()->getId() === $userId;
        });

        return $result->first() ?? null;
    }

    public function getAnswersByQuestion(Question $question): Collection
    {
        return $this->getAnswers()->filter(function (Answer $answer) use ($question) {
            return $answer->getQuestion()->getId() === $question->getId();
        });
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setExaminationSheet($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getExaminationSheet() === $this) {
                $answer->setExaminationSheet(null);
            }
        }

        return $this;
    }

    public function getStart(): ?DateTimeInterface
    {
        if(!$this->getAnswers()) {
            return null;
        }
        $startValue = (new DateTimeImmutable())->add(new DateInterval('P2Y'));
        $minStart = clone $startValue;
        foreach ($this->getAnswers() as $answer) {
            if($minStart > $answer->getStart()) {
                $minStart = $answer->getStart();
            }
        }
        return $minStart == $startValue ? null : $minStart;
    }

    public function getEnd(): ?DateTimeInterface
    {
        if(!$this->getAnswers()) {
            return null;
        }
        $startValue = (new DateTimeImmutable())->sub(new DateInterval('P100Y'));
        $maxDate = clone $startValue;
        foreach ($this->getAnswers() as $answer) {
            $endDate = $answer->getEnd();
            if($endDate && $maxDate < $endDate) {
                $maxDate = $endDate;
            }
        }
        return $maxDate == $startValue ? null : $maxDate;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        $this->questions->removeElement($question);

        return $this;
    }
}

src/Form/ExaminationSheetType.php
<?php

namespace App\Form;

use App\Entity\Exam;
use App\Entity\ExaminationSheet;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExaminationSheetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('student', EntityType::class, [
                'class' => User::class,
                'choice_label' => function (?User $user) {
                    return $user->getEmail();
                }
            ])
            ->add('exam', EntityType::class, [
                'class' => Exam::class,
                'choice_label' => function (?Exam $exam) {
                    return $exam->getDescription();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ExaminationSheet::class,
        ]);
    }
}

src/Controller/ExaminationSheetController.php
<?php

namespace App\Controller;

use App\Entity\ExaminationSheet;
use App\Form\ExaminationSheetType;
use App\Repository\ExaminationSheetRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/examination/sheet')]
class ExaminationSheetController extends AbstractController
{
    #[Route('/', name: 'app_examination_sheet_index', methods: ['GET'])]
    public function index(
        ExaminationSheetRepository $examinationSheetRepository,
        Security $security
    ): Response {
        if (
            in_array('ROLE_TEACHER', $security->getUser()->getRoles())
            || in_array('ROLE_ADMIN', $security->getUser()->getRoles())
        ) {
            return $this->render('examination_sheet/index.html.twig', [
                'examination_sheets' => $examinationSheetRepository->findAll(),
            ]);
        }

        // необхлдимо показывать отлько доступные данному пользователю записи
        return $this->render('examination_sheet/index.html.twig', [
            'examination_sheets' => [],
        ]);
    }

    #[Route('/new', name: 'app_examination_sheet_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ExaminationSheetRepository $examinationSheetRepository): Response
    {
        $examinationSheet = new ExaminationSheet();
        $form = $this->createForm(ExaminationSheetType::class, $examinationSheet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $examinationSheetRepository->add($examinationSheet);
            return $this->redirectToRoute('app_examination_sheet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('examination_sheet/new.html.twig', [
            'examination_sheet' => $examinationSheet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_examination_sheet_show', methods: ['GET'])]
    public function show(ExaminationSheet $examinationSheet): Response
    {
        return $this->render('examination_sheet/show.html.twig', [
            'examination_sheet' => $examinationSheet,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_examination_sheet_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ExaminationSheet $examinationSheet, ExaminationSheetRepository $examinationSheetRepository): Response
    {
        $form = $this->createForm(ExaminationSheetType::class, $examinationSheet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $examinationSheetRepository->add($examinationSheet);
            return $this->redirectToRoute('app_examination_sheet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('examination_sheet/edit.html.twig', [
            'examination_sheet' => $examinationSheet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_examination_sheet_delete', methods: ['POST'])]
    public function delete(Request $request, ExaminationSheet $examinationSheet, ExaminationSheetRepository $examinationSheetRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$examinationSheet->getId(), $request->request->get('_token'))) {
            $examinationSheetRepository->remove($examinationSheet);
        }

        return $this->redirectToRoute('app_examination_sheet_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/examination_sheet/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

    {{ include('components/_actions.html.twig', {
        'action': action,
        'entity': entity | default(null),
        'entityName': 'examination_sheet'
    }) }}

{{ form_end(form) }}

templates/examination_sheet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Edit ExaminationSheet'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Edit ExaminationSheet'|trans }}</h1>

    {{ include('components/_form.html.twig', {
        'action': 'edit',
        'entity': examination_sheet,
        'entityName': 'examination_sheet',
    }) }}

{% endblock %}

templates/examination_sheet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'ExaminationSheet index'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'ExaminationSheet index'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ 'Id'|trans }}</th>
                <th>{{ 'Student'|trans }}</th>
                <th>{{ 'Number of answers'|trans }}</th>
                <th>{{ 'Exam'|trans }}</th>
                <th>{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for examination_sheet in examination_sheets %}
            <tr>
                <td>{{ examination_sheet.id }}</td>
                <td>{{ examination_sheet.student.email }}</td>
                <td>{{ examination_sheet.answers|length }}</td>
                <td>{{ examination_sheet.exam.description }}</td>
                <td>
                    {{ include('components/_actions.html.twig', {
                        'action': 'list',
                        'entity': examination_sheet,
                        'entityName': 'examination_sheet'
                    }) }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">{{ 'no records found'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_examination_sheet_new') }}">{{ 'Create new'|trans }}</a>
{% endblock %}

templates/examination_sheet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'New ExaminationSheet'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Create new ExaminationSheet'|trans }}</h1>

    {{ include('components/_form.html.twig', {
        'action': 'new',
        'entityName': 'examination_sheet',
    }) }}

{% endblock %}

templates/examination_sheet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'ExaminationSheet'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'ExaminationSheet'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>{{ 'Id'|trans }}</th>
                <td>{{ examination_sheet.id }}</td>
            </tr>
            <tr>
                <th>{{ 'Student'|trans }}</th>
                <td>{{ examination_sheet.getStudent().getName() }}</td>
            </tr>
            <tr>
                <th>{{ 'Exam'|trans }}</th>
                <td>{{ examination_sheet.getExam().getDescription() }}</td>
            </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_TEACHER') or is_granted('ROLE_ADMIN') %}
        {{ include('components/_actions.html.twig', {
            'action': 'show',
            'entity': examination_sheet,
            'entityName': 'examination_sheet'
        }) }}
    {% endif %}


    <table class="table">
        <caption>{{ 'Question'|trans }}</caption>
        <thead>
        <tr>
            <th>{{ 'Ord'|trans }}</th>
            <th>{{ 'Question'|trans }}</th>
            <th>{{ 'Answer'|trans }}</th>
            <th>{{ 'Check right'|trans }}</th>
            <th>{{ 'Start'|trans }}</th>
            <th>{{ 'End'|trans }}</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% set sortedAnswers = examination_sheet.getAnswers()|sort((answer, answerNext) => answer.end <=> answerNext.end) %}
        {% for answer in sortedAnswers|sort((answer, answerNext) => answer.getQuestion().ord <=> answerNext.getQuestion().ord) %}
            <tr>
                <td>{{ answer.getQuestion().ord }}</td>
                <td>{{ answer.getQuestion().getContent() }}</td>
                <td>{{ answer.getSqlText() }}</td>
                <td>{{ answer.checkRight }}</td>
                <td>{{ answer.getStart().format('d.m.Y H:i:s') }}</td>
                <td>{% if answer.getEnd() %}{{ answer.getEnd().format('d.m.Y H:i:s') }}{% endif %}</td>
                <td>
                    {{ include('components/_actions.html.twig', {
                        'action': 'list',
                        'entity': answer,
                        'entityName': 'answer'
                    }) }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{{ 'no records found'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}